[project]
name = "space"
version = "0.1.0"
description = "image embedding space"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio",
    "numpy",
    "pillow",
    "plotly",
    "scikit-learn",
    "torch",
    "torchvision",
    "tqdm",
    "transformers",
    "umap-learn",
]
